@ cdecl CreateIpcMutex(ptr)
@ cdecl CreateIpcEvent(ptr long)
@ cdecl CreateIpcSharedMemory(ptr long)
@ cdecl CreateIpcBroadcast(ptr)
@ cdecl DestroyIpcMutex(ptr)
@ cdecl IpcMutex_Lock(ptr)
@ cdecl IpcMutex_TryLock(ptr)
@ cdecl IpcMutex_Unlock(ptr)
@ cdecl IpcMutex_GetNativeHandle(ptr)
@ cdecl DestroyIpcEvent(ptr)
@ cdecl IpcEvent_Set(ptr)
@ cdecl IpcEvent_Wait(ptr long)
@ cdecl IpcEvent_Reset(ptr)
@ cdecl IpcEvent_GetNativeHandle(ptr)
@ cdecl DestroyIpcSharedMemory(ptr)
@ cdecl IpcSharedMemory_Map(ptr)
@ cdecl IpcSharedMemory_Unmap(ptr)
@ cdecl IpcSharedMemory_GetNativeHandle(ptr)
@ cdecl DestroyIpcBroadcast(ptr)
@ cdecl IpcBroadcast_Wait(ptr long)
@ cdecl IpcBroadcast_NotifyAll(ptr)